#!/bin/sh
source /opt/intel/vtune_amplifier_xe_2017/amplxe-vars.sh

amplxe-cl -collect-with runsa -knob event-config=INST_RETIRED.ANY,CPU_CLK_UNHALTED.THREAD,MEM_UOPS_RETIRED.ALL_LOADS,MEM_LOAD_UOPS_RETIRED.L1_HIT,MEM_LOAD_UOPS_RETIRED.L2_HIT,MEM_LOAD_UOPS_RETIRED.L3_HIT,MEM_LOAD_UOPS_RETIRED.L1_MISS,MEM_LOAD_UOPS_RETIRED.L2_MISS,MEM_LOAD_UOPS_RETIRED.L3_MISS $1
